channels:
- conda-forge
dependencies:
- python=3.12.10
- pip<=25.0.1
- pip:
  - mlflow==2.18.0
  - cloudpickle==3.1.2
  - numpy==2.3.4
  - pandas==2.3.3
  - scikit-learn==1.5.2
  - scipy==1.16.3
name: mlflow-env